version: '2'
services:
  solr:
    image: am_solr
    container_name: my_solr
    ports:
     - "8983:8983"
    volumes:
      - data:/opt/solr/server/solr/mycores/
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - Articles

volumes:
  data: